### ISSUE TITLE
Add netjson to the benchmark 

### ISSUE THREAD

**Issue by rpgmaker** [ngs-doo/json-benchmark#2]
I believe i have resolved the issue, Can you try the API again using 1.0.5 and let me know if the problem was resolved.

Thanks,

**Comment by zapov** [comment]
btw. I added vanilla POCO classes to bench.
Now your lib works on some tests, still does not on others (and in some cases on Mono).

**Comment by rpgmaker** [comment]
What are the specific of the one that does not work? Are they types such as
non public members of the class or are they special type?

Thanks,

**Comment by zapov** [comment]
Everything is public as property with data contracts.

in app run: JsonBenchmark.exe NetJSON Standard Check 100

System.EntryPointNotFoundException: Entry point was not found.
   at System.Collections.Generic.ICollection`1.Add(T item)
   at DeletePostClass.CreateListListNullableBoolean(Char* , Int32& )
   at DeletePostClass.SetDeletePost(Char* , Int32& , DeletePost , String )
   at DeletePostClass.CreateClassOrDictDeletePost(Char* , Int32& )
   at DeletePostClass.ReadDeletePost(String )

**Comment by rpgmaker** [comment]
Ok. That make sense. I am working on nullable been added to collection, I
have not fully worked it out yet.

Thanks,
