### ISSUE TITLE
Please update for latest version of JIL and JSON.NET :)

### ISSUE THREAD

**Issue by niemyjski** [ngs-doo/json-benchmark#5]

**Comment by zapov** [comment]
Yeah, I planed on updating bench for a while...
Will do probably next week.

btw. just tried latest versions and... they seem to be around the same speed as before (some things are slightly faster, some things slightly slower)
Jil still fails the standard bench ;(

You can do the same by replacing binaries in app folder and running the command line app.

**Comment by zapov** [comment]
Updated. Not sure what to do about incorrect results with libraries.
I'm not interested in fixing bugs in other people libraries, but people assume I'm doing something wrong since their favorite library doesn't work correctly ;(

**Comment by zapov** [comment]
I've taken a look at Jil again... and it seems its working now on standard, but doesn't work correctly on the large bench. I'll include it in results.

**Comment by niemyjski** [comment]
Yeah I feel you. I created a Jill issue about supporting iset.. Then a year later after lots of complaints they added it

**Comment by zapov** [comment]
I think it's done now.
Let me know if you find some issue with it.
