### ISSUE TITLE
.NET LargeObjectHeapCompactionMode

### ISSUE THREAD

**Issue by KindDragon** [ngs-doo/json-benchmark#6]
Have you tried with LargeObjectHeapCompactionMode?

https://msdn.microsoft.com/en-us/library/system.runtime.gcsettings.largeobjectheapcompactionmode.aspx

**Comment by zapov** [comment]
No, but I doubt it would help.
Only place where that would make sense is large bench, but it does only up to 1000 runs.
There is no GC.Collect() inside bench, since it starts, loops through it requested number of times and exit.

Feel free to try and get back with results.

**Comment by KindDragon** [comment]
Ok, thanks for info
